# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Creating OpenStack Identity Service
  environment: "{{openstack_env}}"
  command: "{{item}}"
  with_items:
  - openstack service create --name keystone --description "OpenStack Identity" identity
  #- openstack service create --name ec2 --description "EC2 Compatibility Layer" ec2


- name: Creating OpenStack Identify Endpoint
  environment: "{{openstack_env}}"
  command: "{{item}}"
  with_items:
  # Identify v3
  - openstack endpoint create --region "{{region}}" identity public http://{{public_addr}}:5000/v3
  - openstack endpoint create --region "{{region}}" identity internal http://{{controller_addr}}:5000/v3
  - openstack endpoint create --region "{{region}}" identity admin http://{{controller_addr}}:35357/v3
  # EC2
  #- openstack endpoint create --region "{{region}}" ec2 public http://{{public_addr}}:8773/services/Cloud
  #- openstack endpoint create --region "{{region}}" ec2 internal http://{{controller_addr}}:8773/services/Cloud
  #- openstack endpoint create --region "{{region}}" ec2 admin http://{{controller_addr}}:8773/services/Admin


- name: Creating OpenStack basic Domain, Projects, Users and Roles
  environment: "{{openstack_env}}"
  command: "{{item}}"
  with_items:
  - openstack domain create --description "Default Domain" default
  - openstack project create --domain default --description "Admin Project" admin
  - openstack user create --domain default --password "{{admin_password}}" --email admin@{{your_domain}} admin
  - openstack role create admin
  - openstack role add --project admin --user admin admin
  - openstack project create --domain default --description "Service Project" service
  - openstack project create --domain default --description "Demo Project" demo
  - openstack user create --domain default --password "{{demo_password}}" --email demo@{{your_domain}} demo
  - openstack role create user
  - openstack role add --project demo --user demo user
