# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# The following hosts definitions, deploys OpenStack:
#

- hosts: os_aio
  user: "{{ubuntu_user}}"
  become: yes
  roles:
  - role: bootstrap
  - role: os_clients
  - role: ssh_keypair
  - role: os_mysql
  - role: os_mysql_db
#  - role: os_mongodb
  - role: os_rabbitmq
  - role: os_memcached
  - role: apache2
  - role: os_keystone
  - role: os_glance
  - role: os_glance_images
  - role: hyper_kvm
  - role: os_nova_ctrl
  - role: os_nova_cmpt
  - role: os_keypair
  - role: os_nova_flavors
  - role: os_neutron_ctrl
  - role: os_ext_net
  - role: os_neutron_net
  - role: os_horizon
#  - role: os_cinder
  - role: os_heat
#  - role: os_manila
#  - role: os_ceilometer

- hosts: os_controller_nodes
  user: "{{ubuntu_user}}"
  become: yes
  roles:
  - role: bootstrap
  - role: os_clients
  - role: ssh_keypair
  - role: os_mysql
  - role: os_mysql_db
#  - role: os_mongodb
  - role: os_rabbitmq
  - role: os_memcached
  - role: apache2
  - role: os_keystone
  - role: os_glance
  - role: os_glance_images
  - role: os_nova_ctrl
  - role: os_keypair
  - role: os_nova_flavors
  - role: os_neutron_ctrl
  - role: os_ext_net
  - role: os_horizon
#  - role: os_cinder
  - role: os_heat
#  - role: os_manila
#  - role: os_ceilometer

- hosts: os_network_nodes
  user: "{{ubuntu_user}}"
  become: yes
  roles:
  - role: bootstrap
  - role: os_neutron_net

- hosts: os_compute_nodes
  user: "{{ubuntu_user}}"
  become: yes
  roles:
  - role: bootstrap
  - role: hyper_kvm
  - role: os_nova_cmpt
  - role: os_neutron_cmpt

- hosts: os_vagrant_aio
  user: "{{ubuntu_user}}"
  become: yes
  roles:
  - role: bootstrap
  - role: os_clients
  - role: ssh_keypair
  - role: os_mysql
  - role: os_mysql_db
#  - role: os_mongodb
  - role: os_rabbitmq
  - role: os_memcached
  - role: apache2
  - role: os_keystone
  - role: os_glance
  - role: os_glance_images
  - role: hyper_kvm
  - role: os_nova_ctrl
  - role: os_nova_cmpt
  - role: os_keypair
  - role: os_nova_flavors
  - role: os_neutron_ctrl
  - role: os_ext_net
  - role: os_neutron_net
  - role: os_horizon
#  - role: os_cinder
  - role: os_heat
#  - role: os_manila
#  - role: os_ceilometer
