# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# References:
# http://docs.openstack.org/mitaka/install-guide-ubuntu/neutron-compute-install.html
# http://docs.openstack.org/mitaka/install-guide-ubuntu/neutron-compute-install-option2.html

- name: Installing Neutron Linux Bridge Agent
  apt: name=neutron-linuxbridge-agent state=latest
  when: br_mode == 'LBR'
  notify: restart-neutron-lbr

- name: Installing Neutron Open vSwitch Agent
  apt: name=neutron-openvswitch-agent state=latest
  when: br_mode == 'OVS'
  notify: restart-neutron-ovs


- name: Updating neutron.conf
  template: src={{openstack_release}}/neutron.conf
            dest=/etc/neutron/neutron.conf
            owner=root
            group=neutron
            mode=0640
            backup=yes
  when: item.os_project == "neutron"
  with_items: mysql_databases


- name: Updating linuxbridge_agent.ini
  template: src={{openstack_release}}/ml2/linuxbridge_agent.ini
            dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini
            owner=root
            group=neutron
            mode=0640
            backup=yes
  when: br_mode == 'LBR'
  notify: restart-neutron-lbr


- name: Updating openvswitch_agent.ini
  template: src={{openstack_release}}/ml2/openvswitch_agent.ini
            dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini
            owner=root
            group=neutron
            mode=0640
            backup=yes
  when: br_mode == 'OVS'
  notify: restart-neutron-ovs


- name: Write custom sysctl.conf
  copy: src=sysctl.conf
        dest=/etc/sysctl.conf
        owner=root
        group=root
        mode=0644
        backup=yes
  when: br_mode == 'LBR'
  notify: reload-sysctl


- meta: flush_handlers
