# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Creating OpenStack Cinder Service
  environment: "{{admin_openrc_env}}"
  command: "{{item}}"
  with_items:
  #- openstack service create --name cinder --description "OpenStack Block Storage" volume
  - openstack service create --name cinderv2 --description "OpenStack Block Storage" volumev2


- name: Creating OpenStack Cinder Endpoint
  environment: "{{admin_openrc_env}}"
  command: "{{item}}"
  with_items:
  - openstack endpoint create --region "{{region}}" volumev2 public http://{{public_addr}}:8776/v2/%\(tenant_id\)s
  - openstack endpoint create --region "{{region}}" volumev2 internal http://{{controller_addr}}:8776/v2/%\(tenant_id\)s
  - openstack endpoint create --region "{{region}}" volumev2 admin http://{{controller_addr}}:8776/v2/%\(tenant_id\)s


- name: Creating OpenStack Cinder User and Role
  environment: "{{admin_openrc_env}}"
  command: "{{item}}"
  with_items:
  - openstack user create --domain default --password "{{service_password}}" --email cinder@{{your_domain}} cinder
  - openstack role add --project service --user cinder admin
